EEPROMManager
ReadMode
DataIOState
ClearMode
ResultStringBuilderSpecification
FormatTarget
constexpr int EEPROMManager::TIME_WAIT_READ
Rappresenta una direttiva del preprocessore moderna indicante il tempo che trascorre tra l'invio del segnale di output enable al chip e l'effettiva presenza di dati campionabili sui pin di IO
Referenced by readAddress, readSegment, writeAddress, writeSegment, hardClear.
constexpr int EEPROMManager::TIME_RECOVERY_FROM_READ
Rappresenta una direttiva del preprocessore moderna indicante per quanto tempo il chip risulta inibito dopo il completamento di una lettura (completata nel momento in cui viene disattivato l'output enable)
Referenced by readAddress, readSegment, writeAddress, writeSegment, hardClear.
constexpr int EEPROMManager::TIME_HOLD_WRITE_SIGNAL
Rappresenta una direttiva del preprocessore moderna indicante per quanto tempo bisogna tenere attivo il segnale write enable per far effettivamente iniziare un ciclo di scrittura al chip
Referenced by writeAddress, writeSegment, hardClear.
constexpr int EEPROMManager::TIME_RECOVERY_FROM_WRITE
Rappresenta una direttiva del preprocessore moderna indicante per quanto tempo il chip risulta inibito dopo il completamento di una scrittura (completata nel momento in cui viene completato un intero ciclo di scrittura)
Referenced by writeAddress, writeSegment, hardClear.
constexpr int EEPROMManager::IMPRECISION
Rappresenta una direttiva del preprocessore moderna indicante approssimativamente la possibile imprecisione del chip in termini di temporizzazione
Referenced by readAddress, readSegment, writeAddress, writeSegment, hardClear.
constexpr int EEPROMManager::ADDRESSING_PIN
Rappresenta una direttiva del preprocessore moderna indicante il numero di pin di indirizzamento da cui è composto il chip
Referenced by init, setAddress.
constexpr int EEPROMManager::DATA_EXCHANGING_PIN
Rappresenta una direttiva del preprocessore moderna indicante il numero di pin di IO da cui è composto il chip
Referenced by setDataIO, sample, put.
constexpr int EEPROMManager::SEGMENT_DEPTH
Rappresenta una direttiva del preprocessore moderna indicante la profondità di ogni singolo segmento di memoria (serie di singoli indirizzi di memoria)
Referenced by readSegment, readAll, writeSegment, writeAll, hardClear, isReadonly.
constexpr bool EEPROMManager::READONLY_SEGMENTS_ALLOWED
Rappresenta una direttiva del preprocessore moderna indicante lo stato di abilitazione del permesso di presenza di segmenti readonly
Referenced by isReadonly.
constexpr int EEPROMManager::READONLY_SEGMENTS
Rappresenta una direttiva del preprocessore moderna indicante il numero di segmenti readonly attivi
Referenced by isReadonly.
constexpr int EEPROMManager::PADDING_CHECK_ONE
Rappresenta una direttiva del preprocessore moderna utilizzata per eseguire il padding dell'output EEPROMManager::format()
Referenced by format.
constexpr int EEPROMManager::PADDING_CHECK_TWO
Rappresenta una direttiva del preprocessore moderna utilizzata per eseguire il padding dell'output EEPROMManager::format()
Referenced by format.
constexpr int EEPROMManager::ADDRESSES
Rappresenta una direttiva del preprocessore moderna indicante il numero di indirizzi totali (i quali non sono tutti raggiungibili. Quelli raggiungibili risiedono nel range 0 (ADDRESSES - 1))
Referenced by readAll, writeAll, hardClear.
constexpr int EEPROMManager::LOWEST_ADDRESS
Rappresenta una direttiva del preprocessore moderna indicante l'indirizzo più basso (con valore algebricamente più alto) raggiungibile
Referenced by readAddress, readSegment.
constexpr int EEPROMManager::HIGHEST_ADDRESS
Rappresenta una direttiva del preprocessore moderna indicante l'indirizzo più alto (con valore algebricamente più basso) raggiungibile
Referenced by readAddress, readSegment, writeAddress, writeSegment.
constexpr int EEPROMManager::VALID_DATA_VALUES
Rappresenta una direttiva del preprocessore moderna indicante il numero di valori validi realizzabili con il numero di bit del chip (non tutti utilizzabili. Quelli realizzabili risiedono nel range 0 (VALID_DATA_VALUES - 1))
constexpr int EEPROMManager::LOWEST_VALID_DATA_VALUE
Rappresenta una direttiva del preprocessore moderna indicante il valore algebricamente più basso realizzabile con il numero di bit del chip
Referenced by writeAddress, writeSegment, writeAll.
constexpr int EEPROMManager::HIGHEST_VALID_DATA_VALUE
Rappresenta una direttiva del preprocessore moderna indicante il valore algebricamente più alto realizzabile con il numero di bit del chip
Referenced by writeAddress, writeSegment, writeAll.
const int EEPROMManager::outputEnable
Rappresenta il pin utilizzato per l'output del segnale di output enable verso il chip
const int EEPROMManager::writeEnable
Rappresenta il pin utilizzato per l'output del segnale di write enable verso il chip
const int* EEPROMManager::addresses
Rappresenta un array di pin utilizzati per l'addressing verso il chip
Referenced by ~EEPROMManager.
const int* EEPROMManager::dataIO
Rappresenta un array di pin utilizzati per l'IO di dati da e verso il chip
Referenced by ~EEPROMManager.
const int* EEPROMManager::readonlySegments
Rappresenta un array di indirizzi base dei segmenti readonly attivi
Referenced by ~EEPROMManager.
bool EEPROMManager::hasBeenInit
Rappresenta un flag booelano indicante lo stato di inizializzazione dell'oggetto "this" in questione
EEPROMManager::EEPROMManager()=delete
EEPROMManager::EEPROMManager(const int &outputEnable, const int &writeEnable, const int &a0, const int &a1, const int &a2, const int &a3, const int &a4, const int &a5, const int &a6, const int &a7, const int &a8, const int &a9, const int &a10, const int &io0, const int &io1, const int &io2, const int &io3, const int &io4, const int &io5, const int &io6, const int &io7)
Costruttore.
Inizializza tutte le risorse necessarie ad un oggetto di questa classe outputEnable il pin utilizzato per l'output del segnale di output enable verso il chip writeEnable il pin utilizzato per l'output del segnale di write enable verso il chip a0 il pin di addressing a0 verso il chip a1 il pin di addressing a1 verso il chip a2 il pin di addressing a2 verso il chip a3 il pin di addressing a3 verso il chip a4 il pin di addressing a4 verso il chip a5 il pin di addressing a5 verso il chip a6 il pin di addressing a6 verso il chip a7 il pin di addressing a7 verso il chip a8 il pin di addressing a8 verso il chip a9 il pin di addressing a9 verso il chip a10 il pin di addressing a10 verso il chip io0 il pin di IO di dati io0 da e verso il chip io1 il pin di IO di dati io1 da e verso il chip io2 il pin di IO di dati io2 da e verso il chip io3 il pin di IO di dati io3 da e verso il chip io4 il pin di IO di dati io4 da e verso il chip io5 il pin di IO di dati io5 da e verso il chip io6 il pin di IO di dati io6 da e verso il chip io7 il pin di IO di dati io7 da e verso il chip EEPROMManager::outputEnable EEPROMManager::writeEnable EEPROMManager::addresses EEPROMManager::dataIO EEPROMManager::hasBeenInit EEPROMManager::READONLY_SEGMENTS_ALLOWED EEPROMManager::readonlySegments EEPROMManager::LIST_READONLY_SEGMENTS
EEPROMManager::~EEPROMManager()
Distruttore.
Finalizza tutte le risorse usate da un oggetto di questa classe EEPROMManager::addresses EEPROMManager::dataIO EEPROMManager::readonlySegments
References addresses, dataIO, readonlySegments.
void EEPROMManager::init()
Inizializzatore stabile.
Assegna valori stabili alle risorse HW/SW che necessitano di un valore forzato per il corretto funzionamento- EEPROMManager::hasBeenInit EEPROMManager::setOutputEnable() EEPROMManager::setWriteEnable() EEPROMManager::outputEnable EEPROMManager::writeEnable EEPROMManager::ADDRESSING_PIN EEPROMManager::addresses
References ADDRESSING_PIN, setOutputEnable, setWriteEnable.
Referenced by setup.
void EEPROMManager::readAddress(const int &address, const EEPROMManager::ReadMode &mode)
Effettua la lettura di un singolo indirizzo di memoria.
Il seguente metodo effettua la lettura di un singolo indirizzo di memoria e stampa il risultato utilizzando l'output standard. L'inizializzazione deve essere già stata eseguita address L'indirizzo di memoria da leggere mode La modalità di interpretazione dei dati letti EEPROMManager::hasBeenInit EEPROMManager::HIGHEST_ADDRESS EEPROMManager::LOWEST_ADDRESS EEPROMManager::setDataIO() EEPROMManager::DataIOState EEPROMManager::ReadMode EEPROMManager::setAddress() EEPROMManager::setOutputEnable() EEPROMManager::TIME_WAIT_READ EEPROMManager::IMPRECISION EEPROMManager::sample() EEPROMManager::resultStringBuilder() EEPROMManager::ResultStringBuilderSpecification EEPROMManager::TIME_RECOVERY_FROM_READ
References _INPUT, HIGHEST_ADDRESS, IMPRECISION, INCLUDE_HEADER_INFO, LOWEST_ADDRESS, resultStringBuilder, sample, setAddress, setDataIO, setOutputEnable, TIME_RECOVERY_FROM_READ, TIME_WAIT_READ.
void EEPROMManager::readSegment(const int &baseAddress)
Effettua la lettura di un intero segmento di memoria.
Il seguente metodo effettua la lettura di un intero segmento di memoria e stampa il risultato utilizzando l'output standard. L'inizializzazione deve essere già stata eseguita baseAddress L'indirizzo base del segmento di memoria da leggere EEPROMManager::hasBeenInit EEPROMManager::HIGHEST_ADDRESS EEPROMManager::LOWEST_ADDRESS EEPROMManager::setDataIO() EEPROMManager::DataIOState EEPROMManager::ReadMode EEPROMManager::setAddress() EEPROMManager::setOutputEnable() EEPROMManager::TIME_WAIT_READ EEPROMManager::IMPRECISION EEPROMManager::sample() EEPROMManager::resultStringBuilder() EEPROMManager::ResultStringBuilderSpecification EEPROMManager::TIME_RECOVERY_FROM_READ EEPROMManager::SEGMENT_DEPTH EEPROMManager::format() EEPROMManager::FormatTarget
References _HEX, _INPUT, format, HEADER, HIGHEST_ADDRESS, IMPRECISION, LOWEST_ADDRESS, NOT_HEADER, NOT_INCLUDE_HEADER_INFO, resultStringBuilder, sample, SEGMENT_DEPTH, setAddress, setDataIO, setOutputEnable, TIME_RECOVERY_FROM_READ, TIME_WAIT_READ.
Referenced by readAll.
void EEPROMManager::readAll()
Effettua la lettura dell'intera memoria del chip.
Il seguente metodo effettua la lettura dell'intera memoria del chip e stampa il risultato utilizzando l'output standard. L'inizializzazione deve essere già stata eseguita EEPROMManager::hasBeenInit EEPROMManager::ADDRESSES EEPROMManager::readSegment() EEPROMManager::SEGMENT_DEPTH EEPROMManager::readSegment()
References ADDRESSES, readSegment, SEGMENT_DEPTH.
void EEPROMManager::writeAddress(const int &address, const int &data)
Effettua la scrittura di un singolo indirizzo di memoria.
Il seguente metodo effettua la scrittura di un singolo indirizzo di memoria. L'inizializzazione deve essere già stata eseguita address L'indirizzo di memoria da scrivere data Il valore da scrivere EEPROMManager::hasBeenInit EEPROMManager::HIGHEST_ADDRESS EEPROMManager::LOWEST_ADDRESS EEPROMManager::setDataIO() EEPROMManager::DataIOState EEPROMManager::ReadMode EEPROMManager::setAddress() EEPROMManager::setWriteEnable() EEPROMManager::TIME_WAIT_READ EEPROMManager::IMPRECISION EEPROMManager::put() EEPROMManager::TIME_RECOVERY_FROM_READ EEPROMManager::LOWEST_VALID_DATA_VALUE EEPROMManager::HIGHEST_VALID_DATA_VALUE EEPROMManager::isReadonly() EEPROMManager::TIME_HOLD_WRITE_SIGNAL EEPROMManager::setOutputEnable() EEPROMManager::sampleLowLevel() EEPROMManager::TIME_RECOVERY_FROM_WRITE
References _INPUT, _OUTPUT, HIGHEST_ADDRESS, HIGHEST_VALID_DATA_VALUE, IMPRECISION, isReadonly, LOWEST_VALID_DATA_VALUE, put, sampleLowLevel, setAddress, setDataIO, setOutputEnable, setWriteEnable, TIME_HOLD_WRITE_SIGNAL, TIME_RECOVERY_FROM_READ, TIME_RECOVERY_FROM_WRITE, TIME_WAIT_READ.
void EEPROMManager::writeSegment(const int &baseAddress, const int &data)
Effettua la scrittura di un intero segmento di memoria.
Il seguente metodo effettua la scrittura di un intero segmento di memoria. L'inizializzazione deve essere già stata eseguita baseAddress L'indirizzo base del segmento di memoria da scrivere data Il valore da scrivere EEPROMManager::hasBeenInit EEPROMManager::HIGHEST_ADDRESS EEPROMManager::LOWEST_ADDRESS EEPROMManager::setDataIO() EEPROMManager::DataIOState EEPROMManager::ReadMode EEPROMManager::setAddress() EEPROMManager::setWriteEnable() EEPROMManager::TIME_WAIT_READ EEPROMManager::IMPRECISION EEPROMManager::put() EEPROMManager::TIME_RECOVERY_FROM_READ EEPROMManager::LOWEST_VALID_DATA_VALUE EEPROMManager::HIGHEST_VALID_DATA_VALUE EEPROMManager::isReadonly() EEPROMManager::TIME_HOLD_WRITE_SIGNAL EEPROMManager::setOutputEnable() EEPROMManager::sampleLowLevel() EEPROMManager::TIME_RECOVERY_FROM_WRITE EEPROMManager::SEGMENT_DEPTH
References _INPUT, _OUTPUT, HIGHEST_ADDRESS, HIGHEST_VALID_DATA_VALUE, IMPRECISION, isReadonly, LOWEST_VALID_DATA_VALUE, put, sampleLowLevel, SEGMENT_DEPTH, setAddress, setDataIO, setOutputEnable, setWriteEnable, TIME_HOLD_WRITE_SIGNAL, TIME_RECOVERY_FROM_READ, TIME_RECOVERY_FROM_WRITE, TIME_WAIT_READ.
Referenced by writeAll.
void EEPROMManager::writeAll(const int &data)
Effettua la scrittura dell'intera memoria del chip.
Il seguente metodo effettua la scrittura dell'intera memoria del chip. data Il valore da scrivere L'inizializzazione deve essere già stata eseguita EEPROMManager::hasBeenInit EEPROMManager::LOWEST_VALID_DATA_VALUE EEPROMManager::HIGHEST_VALID_DATA_VALUE EEPROMManager::SEGMENT_DEPTH EEPROMManager::ADDRESSES EEPROMManager::writeSegment()
References ADDRESSES, HIGHEST_VALID_DATA_VALUE, LOWEST_VALID_DATA_VALUE, SEGMENT_DEPTH, writeSegment.
Referenced by clear.
void EEPROMManager::clear(const EEPROMManager::ClearMode &mode)
Effettua la formattazione della memoria del chip.
Il seguente metodo effettua la formattazione della memoria del chip, causando la perdita di tutte le informazioni in esso contenute mode La modalità di formattazione della memoria del chip Il processo di formattazione "clear" causa la perdita di tutte le informazioni contenute nella memoria del chip, eccetto per i segmenti readonly L'inizializzazione deve essere già stata eseguita EEPROMManager::hasBeenInit EEPROMManager::writeAll() EEPROMManager::ClearMode
References HIGHEST_VALUE_FILL, LOWEST_VALUE_FILL, writeAll.
void EEPROMManager::hardClear(const EEPROMManager::ClearMode &mode)
Effettua la formattazione della memoria del chip.
Il seguente metodo effettua la formattazione della memoria del chip, causando la perdita di tutte le informazioni in esso contenute mode La modalità di formattazione della memoria del chip Il processo di formattazione "hardClear" causa la perdita di tutte le informazioni contenute nella memoria del chip, compresi i i segmenti readonly L'inizializzazione deve essere già stata eseguita EEPROMManager::hasBeenInit EEPROMManager::HIGHEST_ADDRESS EEPROMManager::LOWEST_ADDRESS EEPROMManager::setDataIO() EEPROMManager::DataIOState EEPROMManager::ReadMode EEPROMManager::setAddress() EEPROMManager::setWriteEnable() EEPROMManager::TIME_WAIT_READ EEPROMManager::IMPRECISION EEPROMManager::put() EEPROMManager::TIME_RECOVERY_FROM_READ EEPROMManager::LOWEST_VALID_DATA_VALUE EEPROMManager::HIGHEST_VALID_DATA_VALUE EEPROMManager::isReadonly() EEPROMManager::TIME_HOLD_WRITE_SIGNAL EEPROMManager::setOutputEnable() EEPROMManager::sampleLowLevel() EEPROMManager::TIME_RECOVERY_FROM_WRITE EEPROMManager::SEGMENT_DEPTH
References _INPUT, _OUTPUT, ADDRESSES, HIGHEST_VALUE_FILL, IMPRECISION, LOWEST_VALUE_FILL, put, sampleLowLevel, SEGMENT_DEPTH, setAddress, setDataIO, setOutputEnable, setWriteEnable, TIME_HOLD_WRITE_SIGNAL, TIME_RECOVERY_FROM_READ, TIME_RECOVERY_FROM_WRITE, TIME_WAIT_READ.
void EEPROMManager::setAddress(int address)
Seleziona l'indirizzo specificato.
Il seguente metodo seleziona l'indirizzo specificato attraverso un processo di output di segnali sui bus in output dal controllore e in input al chip sui pin di addressing. address L'indirizzo di memoria da selezionare EEPROMManager::readAddress() EEPROMManager::readSegment() EEPROMManager::writeAddress() EEPROMManager::writeSegment() EEPROMManager::hardClear() EEPROMManager::ADDRESSING_PIN EEPROMManager::addresses
References ADDRESSING_PIN.
Referenced by hardClear, readAddress, readSegment, writeAddress, writeSegment.
void EEPROMManager::setOutputEnable(const bool &state)
Cambia lo stato del segnale di output enable verso il chip.
Il seguente metodo cambia lo stato del segnale di output enable verso il chip state Lo stato da impostare per il segnale di output enable verso il chip EEPROMManager::readAddress() EEPROMManager::readSegment() EEPROMManager::writeAddress() EEPROMManager::writeSegment() EEPROMManager::hardClear() EEPROMManager::init() EEPROMManager::outputEnable
Referenced by hardClear, init, readAddress, readSegment, writeAddress, writeSegment.
void EEPROMManager::setWriteEnable(const bool &state)
Cambia lo stato del segnale di write enable verso il chip.
Il seguente metodo cambia lo stato del segnale di write enable verso il chip state Lo stato da impostare per il segnale di write enable verso il chip EEPROMManager::writeAddress() EEPROMManager::writeSegment() EEPROMManager::hardClear() EEPROMManager::init() EEPROMManager::writeEnable
Referenced by hardClear, init, writeAddress, writeSegment.
void EEPROMManager::setDataIO(const DataIOState &state)
Cambia lo stato dei pin IO dal punto di vista del controllore.
Il seguente metodo cambia lo stato dei pin IO dal punto di vista del controllore: EEPROMManager::DataIOState::_INPUT: indica che il controllore riceve segnali provenienti in input dall'esterno, dunque, il chip dovrebbe fornire segnali in output EEPROMManager::DataIOState::_OUTPUT: indica che il controllore invia segnali in output verso l'esterno, dunque, il chip dovrebbe accettare segnali in input. state Lo stato da impostare per i pin IO EEPROMManager::readAddress() EEPROMManager::readSegment() EEPROMManager::writeAddress() EEPROMManager::writeSegment() EEPROMManager::hardClear() EEPROMManager::DataIOState EEPROMManager::DATA_EXCHANGING_PIN EEPROMManager::dataIO
References _INPUT, _OUTPUT, DATA_EXCHANGING_PIN.
Referenced by hardClear, readAddress, readSegment, writeAddress, writeSegment.
double EEPROMManager::sample()
Effettua il campionamento dei dati in output dal chip.
Il seguente metodo effettua il campionamento dei dati in output dal chip. Dunque, il chip dovrebbe fornire segnali in output e il controllore accettare segnali in input. I pin IO del controllore devono essere impostati su modalità EEPROMManager::DataIOState::_INPUT EEPROMManager::readAddress() EEPROMManager::readSegment() EEPROMManager::DATA_EXCHANGING_PIN EEPROMManager::dataIO
References DATA_EXCHANGING_PIN.
Referenced by readAddress, readSegment.
byte EEPROMManager::sampleLowLevel()
Effettua il campionamento low level dei dati in output dal chip.
Il seguente metodo effettua il campionamento solo del dato in uscita dal pin IO7 del chip EEPROM. Questo è necessario per implementare la tecnica del Data Polling (descritta nel dettaglio sopra). I pin IO del controllore devono essere impostati su modalità EEPROMManager::DataIOState::_INPUT EEPROMManager::writeAddress() EEPROMManager::writeSegment() EEPROMManager::hardClear() EEPROMManager::dataIO
Referenced by hardClear, writeAddress, writeSegment.
String EEPROMManager::resultStringBuilder(const int &address, const double &sampleResult, const EEPROMManager::ReadMode &mode, const EEPROMManager::ResultStringBuilderSpecification &specification)
Formatta i dati da visualizzare per ottenere un output a schermo più elegante e semplice da interpretare e permette di effettuare la conversione dei dati da visualizzare in basi differenti.
Il seguente metodo formatta i dati da visualizzare per ottenere un output a schermo più elegante e semplice da interpretare. Inoltre permette di effettuare la conversione dei dati da visualizzare nelle seguenti basi: DEC HEX OCT BIN address L'indirizzo di memoria da includere come informazione nell'output formattato sampleResult Il valore letto dal chip da includere come informazione nell'output formattato mode La modalità di interpretazione dei dati letti: la base specification Indica la presenza o meno di informazioni aggiuntive poste ad arricchire il significato dell'output EEPROMManager::ResultStringBuilderSpecification EEPROMManager::ReadMode EEPROMManager::readAddress() EEPROMManager::readSegment()
References _BIN, _DEC, _HEX, _OCT, ALL, INCLUDE_HEADER_INFO, NOT_INCLUDE_HEADER_INFO.
Referenced by readAddress, readSegment.
String EEPROMManager::format(const int &value, const EEPROMManager::FormatTarget &target)
Formatta i dati da visualizzare per ottenere un output a schermo più elegante e semplice da interpretare.
Il seguente metodo formatta i dati da visualizzare per ottenere un output a schermo più elegante e semplice da interpretare. Viene utilizzata la tecnica del padding, la quale consiste nell'aggiunta di "un numero variabile di zeri" davanti ad altri valori numerici per ottenere un incolonnamento "perfetto". value Il valore numerico al quale applicare un eventuale padding target Il target del padding EEPROMManager::FormatTarget EEPROMManager::PADDING_CHECK_ONE EEPROMManager::PADDING_CHECK_TWO
References HEADER, NOT_HEADER, PADDING_CHECK_ONE, PADDING_CHECK_TWO.
Referenced by readSegment.
void EEPROMManager::put(int data)
Imposta il valore specificato sui pin IO.
Il seguente metodo imposta il valore specificato sui pin IO, scomponendolo nei singoli bit da cui è composto e assegnando ciascuno di essi ad un rispettivo pin IO (rispettando la sequenza MSB - LSB). Dunque, ogni singolo bit avrà il proprio bus e il proprio pin IO. state Il valore da impostare EEPROMManager::DATA_EXCHANGING_PIN EEPROMManager::dataIO EEPROMManager::writeAddress() EEPROMManager::writeSegment() EEPROMManager::hardClear()
References DATA_EXCHANGING_PIN.
Referenced by hardClear, writeAddress, writeSegment.
bool EEPROMManager::isReadonly(const int &baseAddress)
Controlla se l'indirizzo base specificato si riferisce ad un segmento readonly.
Il seguente metodo controlla se l'indirizzo base specificato si riferisce ad un segmento readonly. baseAddress L'indirizzo base da controllare EEPROMManager::READONLY_SEGMENTS_ALLOWED EEPROMManager::READONLY_SEGMENTS EEPROMManager::readonlySegments EEPROMManager::SEGMENT_DEPTH EEPROMManager::writeAddress() EEPROMManager::writeSegment()
References READONLY_SEGMENTS, READONLY_SEGMENTS_ALLOWED, SEGMENT_DEPTH.
Referenced by writeAddress, writeSegment.